freebsd_instance:
  image_family: freebsd-13-2
task:
  install_script: |
    # Update all packages
    pkg update -f
    pkg upgrade -f -y
    # Use bash for the CI scripts
    pkg install -y devel/readline bash cmake autoconf automake libtool devel/pkgconf
  configure_script:
    - cmake -S . -B build -DMATIO_WITH_HDF5=OFF -DMATIO_MAT73=OFF -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1
  build_script:
    - cmake --build build -- -j8
  test_script:
    - ./build/test_snprintf
    - ./build/test_mat -H
    - ./build/test_mat -L
    - ./build/test_mat -V
    - ./build/matdump -v -H
    - ./build/matdump -V
    - ./build/matdump -d ./share/test_file.mat structure
    - ./build/matdump -v ./share/test_file.mat
    - ./build/matdump -v -f whos ./share/test_file.mat
