repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.6
  hooks:
  - id: clang-format
    files: ^src\/.+\.[ch]$
    exclude: ^(src\/fortran\/matio_internal.c|src\/snprintf.c|src\/safe-math.h)$

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
    files: ^src\/.+\.[ch]$
  - id: end-of-file-fixer
    files: ^src\/.+\.[ch]$
  - id: fix-byte-order-marker
    files: ^src\/.+\.[ch]$
