language: c

git:
  depth: 5

matrix:
  include:
    - os: osx
      osx_image: xcode12
      compiler: clang
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - MAX_RANK=3
        - HDF5_VERSION=foo
        - HOMEBREW_DEPLOY=yes
        - HOMEBREW_NO_ANALYTICS=1
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew

before_cache:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$HOMEBREW_DEPLOY" == "yes" ]]; then brew cleanup; fi

before_install: ./.ci/travis_before_install.sh

install: ./.ci/travis_install.sh

before_script: ./.ci/travis_before_script.sh

script: ./.ci/travis_script.sh

after_success: ./.ci/travis_after_success.sh

notifications:
  email: false

sudo: required
