language: c

git:
  depth: 5
  
addons:
  homebrew:
    update: false
    packages:
      - zlib
      - libtool
      - automake
      - hdf5

matrix:
  include:
    - os: osx
      osx_image: xcode12
      compiler: clang
      env:
        - ENABLE_EXTENDED_SPARSE=yes
        - ENABLE_MAT73=yes
        - WITH_ZLIB=yes
        - MAX_RANK=3
        - HDF5_VERSION=foo
        - HOMEBREW_NO_ANALYTICS=1

before_install: ./.ci/travis_before_install.sh

install: ./.ci/travis_install.sh

before_script: ./.ci/travis_before_script.sh

script: ./.ci/travis_script.sh

after_success: ./.ci/travis_after_success.sh

notifications:
  email: false

sudo: required
