name: "Autotools build"

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc
          - toolchain: macos-clang
            os: macos-latest
            compiler: clang
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 5
          submodules: recursive
      - name: Install dependencies
        if: matrix.toolchain == 'macos-clang'
        run: brew install automake autoconf libtool
      - name: Install hdf5
        timeout-minutes: 5
        run: |
          FILENAME=$(wget -qO- https://github.com/HDFGroup/hdf5/releases/download/snapshot/last-file.txt | head -n 1)
          wget --no-check-certificate -nv https://github.com/HDFGroup/hdf5/releases/download/snapshot/${FILENAME}.tar.gz
          tar -xzf ${FILENAME}.tar.gz
          cd hdfsrc
          cmake -S . -B build -DHDF5_BUILD_EXAMPLES=OFF -DBUILD_LZ4_LIBRARY_SOURCE=OFF -DHDF5_BUILD_HL_LIB=OFF -DHDF5_BUILD_TOOLS=OFF -DHDF5_ENABLE_DEPRECATED_SYMBOLS=OFF -DHDF5_ENABLE_PREADWRITE=OFF -DHDF5_ENABLE_NONSTANDARD_FEATURES=OFF -DHDF5_DEFAULT_API_VERSION=v200 -DBUILD_TESTING=OFF -DHDF5_ENABLE_ALL_WARNINGS=OFF -DHDF5_ENABLE_EMBEDDED_LIBINFO=OFF -DHDF5_ENABLE_ZLIB_SUPPORT=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/hdf5
          cmake --build build -- -j8
          cmake --build build --target install
      - name: Configure
        run: |
          ./autogen.sh
          ./configure --enable-shared --enable-mat73 --enable-extended-sparse --with-pic --with-hdf5=${GITHUB_WORKSPACE}/hdf5 CFLAGS="-O3" CPPFLAGS="-DNDEBUG"
      - name: Build with ${{ matrix.compiler }}
        run: make -j8
      - name: Test
        run: |
          if [ "${{ matrix.toolchain }}" == "macos-clang" ]; then
            export DYLD_LIBRARY_PATH="${GITHUB_WORKSPACE}/hdf5/lib:$DYLD_LIBRARY_PATH"
          else
            export LD_LIBRARY_PATH=${GITHUB_WORKSPACE}/hdf5/lib:$LD_LIBRARY_PATH
          fi
          make check
